### ISSUE TITLE
Wrong link on website

### ISSUE THREAD

**Issue by DDeAlmeida** [Narwallets/dapp-diversifying-staking-pool#1]
On https://github.com/Narwallets/meta-pool/blob/master/docs/beta-test.md, the link on "Test the web app, report bugs here github.com/Narwallets/webapp-meta-pool/issues" is incorrect.

The link is https://github.com/Narwallets/dapp-meta-pool/issues 
but the correct one is : https://github.com/Narwallets/webapp-meta-pool/issues

**Comment by DDeAlmeida** [comment]
On https://github.com/Narwallets/webapp-meta-pool ,the link on "There are rewards!!!! check https://github.com/Narwallets/beta-test" is incorrect.

the link is : https://github.com/Narwallets/beta-test
but the correct is : https://github.com/Narwallets/beta-testing

**Comment by luciotato** [comment]
Fixed!
