### ISSUE TITLE
Error Panicked

### ISSUE THREAD

**Issue by DDeAlmeida** [Narwallets/dapp-diversifying-staking-pool#2]
![image](https://user-images.githubusercontent.com/52310650/108375789-9a59a780-7202-11eb-95a9-d8a734e19682.png)
![image](https://user-images.githubusercontent.com/52310650/108375957-c07f4780-7202-11eb-9ca8-6ffef3e855e2.png)

Now i'm stuck. I can't go to my account.

**Comment by luciotato** [comment]
TODO - Make RewardMeter more solid
