### ISSUE TITLE
[webapp] Do not allow amounts <=0 -. Error not Clear when remove 0 liquidity

### ISSUE THREAD

**Issue by DDeAlmeida** [Narwallets/dapp-diversifying-staking-pool#4]
Hi, i try to remove 0 liquidity, yeah i'm stupid but the error is not realy Clear ^^

![image](https://user-images.githubusercontent.com/52310650/108383200-d8a69500-7209-11eb-8bcb-c4f6d26cd0c1.png)

**Comment by luciotato** [comment]
I'll catch that in the webapp, it shouldn't even get to the wallet.

**Comment by luciotato** [comment]
Fixed. Please force download of webapp by pressing Ctrl-F5
