### ISSUE TITLE
feat: [Narwallet] Make protocol error message more User Friendly

### ISSUE THREAD

**Issue by DDeAlmeida** [Narwallets/dapp-diversifying-staking-pool#5]
![image](https://user-images.githubusercontent.com/52310650/108383450-1a374000-720a-11eb-8170-e26f47433fe0.png)

When you try to deposit more than you have in the balance

**Comment by luciotato** [comment]
That message is not generated by the contract, it's from the core-protocol itself when you try to attach 100N to the txn but you only have 99.99 in your near account.- I'll mark this as a feature for narwallet, maybe the wallet can capture and format that message and remove some clutter. Good catch!
